---
title: "R Notebook"
author: "Remington Harris and Cameron Vinson"
date: "May 1st 2019"
output: html_notebook
---

```{r}
rm(list = ls())

library(mosaic)
library(tidyr)
library(readr)
library(tidyverse)
library(rvest)
library(regexPipes)
```

```{r}
page <- "https://en.wikipedia.org/wiki/List_of_countries_by_past_and_future_population"
XPATH <- '//*[@id="mw-content-text"]/div/table[2]' 

table_list <- 
  page %>%
  read_html() %>%
  html_nodes(xpath = XPATH) %>%
  html_table(fill = TRUE)

Pop_Country <- table_list[[1]] 

head(Pop_Country)
```

```{r}
index <- as.character(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

colnames(Pop_Country) <- index

Pop_Country <-
  Pop_Country %>%
  rename(
    Country = `1`,
    `1985 Pop` = `2`,
    `1990 Pop` = `4`,
    `1995 Pop` = `6`,
    `2000 Pop` = `8`,
    `2005 Pop` = `10`,
    `2010 Pop` = `12`,
    `2015 Pop` = `14`) %>%
  select(Country, `1985 Pop`, `1990 Pop`, `1995 Pop`, `2000 Pop`, `2005 Pop`, `2010 Pop`, `2015 Pop`)

head(Pop_Country)
```


```{r}
page_url <- "http://edgar.jrc.ec.europa.eu/overview.php?v=CO2ts_pc1990-2013"
XPATH <- '//*[@id="layout"]/div[3]/div[2]/div/div/div/div/table'

table_list <-
  page_url %>%
  read_html() %>%
  html_nodes(xpath = XPATH) %>%
  html_table(fill = TRUE)

CarbonRaw <-
  table_list[[1]]

head(CarbonRaw)
```

```{r}
colnames(CarbonRaw) <-
  as.character(unlist(CarbonRaw[1,]))

CarbonRaw2 <-
  CarbonRaw[-1, ]

CarbonRaw3 <-
  CarbonRaw2[-1, ]

CarbonRaw4 <-
  CarbonRaw3 %>%
  rename(`1990` = `1990TonsCO2/cap4.267`,
         `1995` = `1995TonsCO2/cap4.120`,
         `2000` = `2000TonsCO2/cap4.146`,
         `2005` = `2005TonsCO2/cap4.513`,
         `2010` = `2010TonsCO2/cap4.780`,
         `2011` = `2011TonsCO2/cap4.870`,
         `2012` = `2012TonsCO2/cap4.894`,
         `2013` = `2013TonsCO2/cap4.936`)
```

```{r}
head(CarbonRaw4)
```

```{r}
CarbonCleaned <-
  CarbonRaw4 %>%
  transmute(`Country` = `CountryWorld Total`,
         `1990 Emissions` = as.numeric(CarbonRaw4$`1990`),
         `1995 Emissions` = as.numeric(CarbonRaw4$`1995`),
         `2000 Emissions` = as.numeric(CarbonRaw4$`2000`),
         `2005 Emissions` = as.numeric(CarbonRaw4$`2005`),
         `2010 Emissions` = as.numeric(CarbonRaw4$`2010`)
         ) 

head(CarbonCleaned)
```
%>%
  regexPipes::sub("Korea, Democratic People's Republic of", "South Korea")
  
```{r}
CarbonCleaned$Country <-
  CarbonCleaned$Country %>%
  regexPipes::sub("Korea, Democratic People's Republic of", "South Korea") %>%
  regexPipes::sub("Korea, Republic of", "North Korea") %>%
  regexPipes::sub("Lao People's Democratic Republic", "Laos") %>%
  regexPipes::sub("Macedonia, the former Yugoslav Republic of", "North Macedonia") %>%
  regexPipes::sub("Libyan Arab Jamahiriya", "Libya") %>%
  regexPipes::sub("Macao", "Macau") %>%
  regexPipes::sub("Moldova, Republic of", "Moldova") %>%
  regexPipes::sub("Russian Federation", "Russia") %>%
  regexPipes::sub("Congo_the Democratic Republic of the", "Democratic Republic of the Congo") %>%
  regexPipes::sub("Congo", "Republic of the Congo") %>%
  regexPipes::sub("Democratic Republic of the Republic of the Congo", "Democratic Republic of the Congo") %>%
  regexPipes::sub("Cote d'Ivoire", "Ivory Coast") %>%
  regexPipes::sub("Iran, Islamic Republic of", "Iran") %>%
  regexPipes::sub("Sao Tome and Principe", "São Tomé and Príncipe") %>%
  regexPipes::sub("Taiwan_Province of China", "Taiwan") %>%
  regexPipes::sub("Tanzania_United Republic of", "Tanzania") %>%
  regexPipes::sub("Syrian Arab Republic", "Syria") %>%
  regexPipes::sub("Viet Nam", "Vietnam") %>%
  regexPipes::sub("Virgin Islands_British", "British Virgin Islands") %>%
  regexPipes::sub("Virgin Islands_USA", "United States Virgin Islands") %>%
  regexPipes::sub("Brunei Darussalam", "Brunei")


```
  
```{r}
JoinedTable<-
  CarbonCleaned %>%
  left_join(Pop_Country, by = "Country")
```































































































































